<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__iframeResult</name>
   <tag></tag>
   <elementGuidId>41ba2277-7e02-4322-8503-45131efd3d4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframeResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2983f4d5-cf5a-46a7-8ed5-7c08d58e96a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d22284d6-58e1-4510-bc76-27241f90ac01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeResult</value>
      <webElementGuid>3b2f64e1-21af-499a-ae2f-21239c340529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframeResult</value>
      <webElementGuid>61d4be7d-1a3e-4962-b0a4-9091bf8c8698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac99f083-e6a2-4906-943b-84e5c6fc41f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeResult&quot;)</value>
      <webElementGuid>e077e54c-f7f8-41fc-a876-41d7b6de887a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeResult']</value>
      <webElementGuid>24cbc7cd-e4b8-4387-956a-a5b408903ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframewrapper']/iframe</value>
      <webElementGuid>55daa27d-8652-45db-bbcd-6f313b3d532d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/iframe</value>
      <webElementGuid>d13b2b83-7c81-479f-9acc-bafaaf997f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeResult' and @name = 'iframeResult']</value>
      <webElementGuid>ac05812d-d33b-4ce3-bdb2-79f26fda6c82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
